elastic/curator

- curator/curator.py
- test_curator/integration/test_utils.py
> not updating replicase if not needed

- curator/curator.py
Issue discovered in https://github.com/elasticsearch/curator/issues/259#issuecomment-72548931
Apologies for the empty line pruning.  I switched to using Atom as my editor.
closes #264
> Fix segment count for empty index

- CONTRIBUTORS
- Changelog.rst
More apologies for the empty line pruning (Switched to Atom)
> Bump for changes in #265

- CONTRIBUTORS
- Changelog.rst
- curator/curator.py
- test_curator/integration/test_utils.py
Not just my 1.x dev branch.
closes #267
> Bloom filters were disabled in 1.4

- curator/curator.py
Currently it can take a long time to apply index allocation rules with curator if there are many indices (like >10 minutes for 4 weeks' worth of hourly indices). This patch adds a check to see if the index already has the allocation rule to be set, and if yes, it skips the index. It made the above example finish just under 9 seconds.
Feel free to ask for followup changes if required, and please indicate if signing the CLA is required for accepting this contribution.
> Skip already allocated indices

- .gitignore
- curator/api/alias.py
- curator/api/bloom.py
- curator/api/close.py
- curator/api/delete.py
- curator/api/opener.py
- curator/api/optimize.py
- curator/api/replicas.py
- curator/api/snapshot.py
- curator/api/utils.py
- curator/cli/utils.py
- setup.py
- test/unit/test_api_commands.py
- test/unit/test_api_filter.py
Lots of changes, but tests now pass on both platforms
> Made this work with python3

- curator/_version.py
- test/integration/test_cli_commands.py
Were using the wrong host and port
> Fix cli integration tests

- curator/cli/optimize.py
- curator/cli/snapshot.py
It was nearly 2 orders of magnitude bigger than it should have been.
> Writing docs caught the incorrect timeout

- Changelog.rst
- curator/api/filter.py
- curator/cli/index_selection.py
- curator/cli/snapshot_selection.py
- docs/examples.rst
- docs/filters.rst
- docs/index.rst
- test/unit/test_api_filter.py
Renamed regex_iterate method and changed all tests and methods accordingly
Added build_filter method
Added unit tests for build_filter
Added example documentation
Added build_filter to filters.rst
Updated Changelog
> Addresses concerns raised in #297

- docs/examples.rst
> Replace filter with _filter

- CONTRIBUTORS
- Changelog.rst
- curator/cli/snapshot.py
> Address issues raised in #303

- curator/cli/es_repo_mgr.py
- curator/cli/index_selection.py
- curator/cli/utils.py
- test/integration/test_cli_commands.py
- test/integration/test_es_repo_mgr.py
- test/unit/test_es_repo_mgr.py
> Repo mgr tests

- LICENSE.txt
> Update license holder to be Elasticsearch

- curator/cli/es_repo_mgr.py
> Increase timeout for snapshot and node discovery

- Changelog.rst
- curator/api/filter.py
- curator/api/utils.py
- curator/cli/cli.py
- curator/cli/utils.py
- docs/utilities.rst
- test/integration/test_cli_commands.py
Moved the chunk_index_list to api/utils
Added tests
Made nested/inline method to extract stats
> This PR re-fixes #245 for delete by space

- docs/asciidoc/misc/faq.asciidoc
> Added FAQ to address setuptools issues

- test/integration/__init__.py
> Update client timeout to prevent Jenkins issues

- test/integration/test_cli_commands.py
> Shrink the index count by using huge names

- docs/asciidoc/commands/optimize.asciidoc
> Added optimize space usage notice

- docs/asciidoc/misc/faq.asciidoc
> Add another FAQ, regarding gateway timeouts

- docs/asciidoc/flags/newer-than.asciidoc
> Fix newer-than flag description

- Changelog.rst
- docs/asciidoc/flags/dry-run.asciidoc
- docs/asciidoc/flags/timestring.asciidoc
> Documentation changes.

- curator/api/snapshot.py
- docs/asciidoc/commands/show.asciidoc
And a doc that got missed in #378 
fixes #379
> Fix for tests on old versions of ES

- curator/api/snapshot.py
- test/unit/test_api_commands.py
Updated to test for version, since older than 1.1 seems to be the
problem area.
fixes #379
> This time it should work.

- Changelog.rst
- curator/api/replicas.py
- curator/api/utils.py
- curator/cli/cli.py
- curator/cli/es_repo_mgr.py
- curator/cli/index_selection.py
- curator/cli/snapshot_selection.py
- docs/asciidoc/misc/exitcodes.asciidoc
- test/integration/test_api_commands.py
- test/integration/test_cli_commands.py
This is a sort of omnibus collection of patches I was working on at once.  The commits are per bug, though.
> Big bundle

- curator/api/replicas.py
> Fixed "empty array" fail for test

- Changelog.rst
- curator/api/alias.py
- docs/asciidoc/commands/alias.asciidoc
- test/integration/test_api_commands.py
- test/unit/test_api_commands.py
This was requested in #317
Tests updated and code cleaned up.  Unnecessary comments also pruned.
> Alias automatically created if nonexistent

- Changelog.rst
- curator/cli/utils.py
- docs/asciidoc/flags/use_ssl.asciidoc
This feature is _experimental_.  Please submit bug reports if you
encounter issues.
closes #345
> Add experimental SSL cert validation

- Changelog.rst
- curator/api/__init__.py
- curator/api/close.py
- curator/api/seal.py
- curator/cli/__init__.py
- curator/cli/seal.py
- curator/cli/utils.py
- docs/asciidoc/commands/close.asciidoc
- docs/asciidoc/commands/index.asciidoc
- docs/asciidoc/commands/seal.asciidoc
- docs/commands.rst
- test/integration/test_cli_commands.py
- test/unit/test_api_commands.py
Include all documentation and new tests for this.
closes #394
> Add synced flush feature (index sealing)

- Changelog.rst
- curator/cli/es_repo_mgr.py
- test/integration/test_es_repo_mgr.py
Stupid method call missing the client was all.  Test added to check
for 0 exit code.
fixes #389
> Fix verification error

- Changelog.rst
- curator/cli/es_repo_mgr.py
- test/unit/test_es_repo_mgr.py
This should hopefully address the request in #405
> Try to grab upstream error msg

- .gitignore
- MANIFEST.in
- requirements.txt
- setup.cfg
Mainly addresses new python wheel requirements
> Fix packaging bits

- docs/asciidoc/subcommands/index.asciidoc
It was missing in a few places.
> Add the seal command

- CONTRIBUTORS
- Changelog.rst
- curator/api/allocation.py
- curator/api/utils.py
- curator/cli/allocation.py
- curator/cli/utils.py
- test/integration/test_api_commands.py
- test/integration/test_cli_commands.py
- test/unit/test_api_commands.py
Extended the ability to use both include and exclude for allocation strategies.
> Added allocation types: include and exclude

- Changelog.rst
- curator/cli/cli.py
- curator/cli/utils.py
- test/integration/test_cli_utils.py
- test/unit/test_cli_utils.py
* `--ssl-no-validate` Do not validate SSL certificate
* `--certificate` Provide path to your own certificate, otherwise use Certifi, if present.
> Add SSL features

- Changelog.rst
- curator/api/filter.py
- test/unit/test_api_filter.py
> Fix delete by space to consider replica shards too

- Changelog.rst
- curator/cli/snapshot_selection.py
- test/integration/test_cli_commands.py
> Fix exit codes and messages for snapshot selection

- Changelog.rst
- curator/api/filter.py
> Cast variables to prevent API call mishaps

- docs/asciidoc/flags/newer-than.asciidoc
- docs/asciidoc/flags/older-than.asciidoc
> Documentation improvements

- CONTRIBUTORS
- Changelog.rst
- curator/api/utils.py
- curator/cli/index_selection.py
- test/integration/__init__.py
- test/integration/test_api_utils.py
- test/integration/test_cli_commands.py
These are my first steps in python,so please be patient but I needed this filter urgently.
This should hopefully fix #476.
> #476: select only closed indices while filtering

- Changelog.rst
- curator/api/alias.py
- curator/api/filter.py
- curator/api/utils.py
- curator/cli/cli.py
- curator/cli/es_repo_mgr.py
- curator/cli/index_selection.py
> Logging improvements requested in #475

- curator/api/utils.py
- test/unit/test_api_commands.py
- test/unit/test_api_filter.py
- test/unit/test_api_utils.py
> Make index_closed use /_cat/indices instead of /_cluster/state for ES > 1.5.0

- docs/asciidoc/index.asciidoc
- docs/asciidoc/misc/installation.asciidoc
> 3.4.0 docs

- curator/api/snapshot.py
`if name in all_snaps` will raise `TypeError` when `get_snapshots` returns  False.
```
TypeError: argument of type 'bool' is not iterable
```
> return False when failing to get _all snapshots

- curator/api/optimize.py
- docs/Changelog.rst
...if delay is > 0, anyway.
closes #525
> Show time delay between optimize runs

- CONTRIBUTORS
- curator/cli/utils.py
- docs/Changelog.rst
> Change --master-only exit code to 0 when connected to non-master node

- curator/api/snapshot.py
- docs/Changelog.rst
- test/unit/test_api_commands.py
This will show when the repository cannot be reached.
Updated Changelog with some missing entries.
fixes #551
> Improve logging in snapshot api method.

- curator/api/utils.py
- curator/cli/es_repo_mgr.py
- docs/Changelog.rst
- docs/utilities.rst
- test/unit/test_es_repo_mgr.py
Update tests and documentation.
fixes #550
> Move repository creation methods to the API

- CONTRIBUTORS
- curator/cli/snapshot.py
- docs/Changelog.rst
- test/integration/test_cli_commands.py
> Disallow snapshot names with uppercase characters

- curator/utils.py
- docs/Changelog.rst
- docs/asciidoc/configuration.asciidoc
- test/unit/test_utils.py
Added test, cleaned spurious lines from other tests.
Documented this for API and CLI/Usage.
fixes #615
> Disallow `master_only` if multiple hosts

- curator/utils.py
- docs/Changelog.rst
> Fix prune_nones to work with Python 2.6

- CONTRIBUTING.md
- README.rst
- docs/Changelog.rst
- docs/asciidoc/about.asciidoc
- docs/conf.py
Prepare for release of 4.0.0a10
> Update docs for release

- .travis.yml
- README.rst
- curator/utils.py
- setup.py
Added some new configuration options.
> Changes to get Travis CI working

- README.rst
> Use a table

- CONTRIBUTING.md
- docs/asciidoc/actions.asciidoc
> Update docs to correct cut/paste errors

- curator/__init__.py
- curator/es_repo_mgr.py
- curator/repomgrcli.py
- curator/utils.py
- docs/Changelog.rst
- run_es_repo_mgr.py
- setup.py
- test/integration/test_es_repo_mgr.py
This is a stopgap measure until I either add other scripts based on this API, or add repository creation/deletion actions, or both.
It remains undocumented as it was never documented fully before.
fixes #668
> Restore es_repo_mgr endpoint

- docs/asciidoc/filters.asciidoc
else yaml complains (if you blindly copy paste this)
curator.exceptions.ConfigurationError
> Added colon after "field"

- curator/_version.py
- curator/actions.py
- curator/cli.py
- curator/defaults/settings.py
- curator/indexlist.py
- curator/logtools.py
- curator/snapshotlist.py
- curator/utils.py
- docs/Changelog.rst
- docs/asciidoc/configuration.asciidoc
- docs/asciidoc/index.asciidoc
- examples/curator.yml
- test/integration/testvars.py
Fix whitelisting by simplifying and blacklisting instead.
Reduce log level for many messages to DEBUG.
Update docs to reflect blacklisting changes to logging configuration, with examples.
fixes #684
> Logging improvements

- docs/asciidoc/about.asciidoc
- docs/asciidoc/actions.asciidoc
- docs/asciidoc/command-line.asciidoc
- docs/asciidoc/configuration.asciidoc
- docs/asciidoc/faq.asciidoc
- docs/asciidoc/filter_elements.asciidoc
- docs/asciidoc/getting_started.asciidoc
- docs/asciidoc/options.asciidoc
This makes docs more accessible, by adding a menu at each of the top-level docs/chapters.
> Fix some doc issues

- docs/asciidoc/installation.asciidoc
as mentioned in requirements.txt within curator package
> add pyyaml dependency

- README.rst
> This is RST, not Markdown

- docs/asciidoc/index.asciidoc
> Update docs to 4.0.4

- docs/asciidoc/filter_elements.asciidoc
This is just for users understanding
> Add table showing unit values in seconds

- docs/asciidoc/faq.asciidoc
- docs/asciidoc/installation.asciidoc
- docs/asciidoc/options.asciidoc
Fix a few other bits, too.
fixes #715
> Add FAQ regarding the need for creation_date

- curator/defaults/settings.py
- curator/indexlist.py
- curator/snapshotlist.py
- curator/validators/filter_elements.py
- curator/validators/filters.py
- curator/validators/filtertypes.py
- docs/asciidoc/filter_elements.asciidoc
- docs/asciidoc/filters.asciidoc
- test/unit/test_class_index_list.py
- test/unit/test_class_snapshot_list.py
- test/unit/test_validators.py
This allows the list to be pruned down to only _n_ indices or snapshots.
Updated documentation and tests.
closes #649
> Add a "count" filter

- curator/validators/config_file.py
- curator/validators/filter_elements.py
- curator/validators/filters.py
- curator/validators/options.py
- docs/Changelog.rst
...from strings, or numbers, or of course regular True/False.
fixes #765
> Use voluptuous' Boolean() method to coerce bools

- curator/utils.py
- docs/Changelog.rst
- docs/asciidoc/configuration.asciidoc
- docs/asciidoc/faq.asciidoc
> Document AWS IAM incompatibility

- curator/snapshotlist.py
- docs/Changelog.rst
It was omitted by, well, accidental omission.
fixes #766
> Fix omission of count in __map_method

- .gitignore
- Vagrant/centos/6/Vagrantfile
- Vagrant/centos/7/Vagrantfile
- Vagrant/ubuntu/14.04/Vagrantfile
- docs/Changelog.rst
- unix_packages/build_packages.sh
- unix_packages/cx_freeze.setup.py.patch
Vagrantfiles, patches, and build script included.
> Add binary building support

- unix_packages/build_packages.sh
If looping, you need to go back to the PACKAGEDIR
> Add missing line

- docs/Changelog.rst
- docs/asciidoc/command-line.asciidoc
- docs/asciidoc/faq.asciidoc
- run_curator.py
- run_es_repo_mgr.py
- run_singleton.py
Improve error messages, suggestions, and documentation
fixes #814
> click requires Unicode locale with Python3

- curator/singletons.py
- docs/Changelog.rst
This prevents ugly error messages that might be benign
fixes #812
> Add missing "ignore_empty_list" option to actions

- curator/_version.py
- curator/singletons.py
- docs/Changelog.rst
- docs/asciidoc/index.asciidoc
Singleton action should have the same default as the regular action.
Also bump version information
fixes #829
> Change wait_for_completion default for snapshot

- curator/singletons.py
- docs/Changelog.rst
> Catch empty list during filter iteration

- README.rst
Getting Started Link was pointing to 404 page.
> Updated README - Broken Link

- unix_packages/build_official_package.sh
- unix_packages/build_package_from_source.sh
They should be deterministic, not fixed
> Fix build script's $HOME paths

- curator/utils.py
- docs/Changelog.rst
> Add missing repository arg to API docs

- curator/actions.py
- docs/Changelog.rst
- test/integration/test_alias.py
- test/integration/testvars.py
- test/unit/test_action_alias.py
- test/unit/testvars.py
> Check for index/alias association before deleting

- curator/actions.py
- test/integration/test_alias.py
- test/unit/test_action_alias.py
This is required with elasticsearch-py==5.1.0
> Refactor get_aliases to get_alias

- .travis.yml
- curator/actions.py
- curator/cli.py
- curator/defaults/settings.py
- curator/utils.py
- curator/validators/actions.py
- curator/validators/options.py
- docs/Changelog.rst
- docs/asciidoc/actions.asciidoc
- docs/asciidoc/examples.asciidoc
- docs/asciidoc/options.asciidoc
- test/integration/testvars.py
- test/unit/test_utils.py
- test/unit/testvars.py
This feature has been long anticipated.
fixes #898
> Add Rollover action

- curator/actions.py
- curator/validators/options.py
- docs/Changelog.rst
- docs/asciidoc/actions.asciidoc
- docs/asciidoc/options.asciidoc
- requirements.txt
- test/integration/test_allocation.py
- test/unit/test_action_allocation.py
> Allow unsetting of shard allocation w/ empty value

- curator/utils.py
- docs/Changelog.rst
- docs/asciidoc/actions.asciidoc
- docs/asciidoc/options.asciidoc
- requirements.txt
- setup.py
- test/integration/test_create_index.py
And document it, and link that to Elasticsearch's documentation on date math.
fixes #511
> Add date math support to create_index

- curator/utils.py
- docs/Changelog.rst
...rather than just raising an exception (which is less visible).
fixes #874
> Log version incompatibilities

- curator/utils.py
- docs/Changelog.rst
- test/integration/test_es_repo_mgr.py
- test/unit/test_utils.py
> Raise exception instead of returning bool

- curator/singletons.py
Send `max_wait` instead of `timeout`.
fixes #936
> Fix curator_cli allocation action

- docs/Changelog.rst
- docs/asciidoc/configuration.asciidoc
- docs/asciidoc/inc_filepath.asciidoc
> Add file path tips

- curator/actions.py
- curator/defaults/option_defaults.py
- curator/validators/options.py
- test/unit/test_action_rollover.py
Addresses https://github.com/elastic/curator/issues/938
> Add support for new index name in rollover action

- curator/actions.py
- curator/cli.py
- curator/indexlist.py
- curator/utils.py
- docs/Changelog.rst
`is not` should be `!=` when not comparing against `None`.
Also found more places to use `isinstance`, see #973
fixes #972
> Fix equality operator

- curator/actions.py
fixes https://github.com/elastic/curator/issues/1003
> fix repository vs. snapshot name logging message

- curator/utils.py
- docs/Changelog.rst
This is duly described in #992.
fixes #992
> Report curator version properly

- curator/actions.py
- docs/Changelog.rst
- test/integration/test_reindex.py
> Fix post-reindex checks to use date-math

- docs/asciidoc/actions.asciidoc
- docs/asciidoc/options.asciidoc
Didn't like how the other turned out, and had a few things to clean up
> Update examples again

- docs/Changelog.rst
- docs/asciidoc/installation.asciidoc
Also, release prep for 5.1.2
fixes #998
fixes #1014
> Fix release docs with new debian9 repo info

- .travis.yml
- curator/cli.py
- docs/Changelog.rst
> Split cli into "run" and "cli" functions

- docs/Changelog.rst
- docs/asciidoc/actions.asciidoc
> Fix doc build issue

- curator/defaults/option_defaults.py
- docs/Changelog.rst
> Add batch size to schema for reindex request_body

- CONTRIBUTORS
- curator/_version.py
- curator/actions.py
- curator/indexlist.py
- docs/Changelog.rst
- docs/actionclasses.rst
- docs/asciidoc/filters.asciidoc
- docs/asciidoc/index.asciidoc
Add missing contributors, and bump the version to rc1
> Doc fixes for asciidoc and rST

- test/integration/test_shrink.py
I can't believe these didn't get added.  Well, here they are now.
> Add shrink tests

- curator/defaults/filter_elements.py
- curator/defaults/filtertypes.py
- curator/defaults/settings.py
- curator/indexlist.py
- docs/Changelog.rst
- docs/asciidoc/filter_elements.asciidoc
- docs/asciidoc/filters.asciidoc
- test/integration/test_delete_indices.py
- test/integration/testvars.py
Also fix a bad integration test.
All docs added as well.
fixes #1045
> Add intersect per #1045

- .travis.yml
- curator/defaults/filter_elements.py
- curator/defaults/filtertypes.py
- curator/defaults/settings.py
- curator/indexlist.py
- docs/Changelog.rst
- docs/asciidoc/filter_elements.asciidoc
- docs/asciidoc/filters.asciidoc
- test/integration/test_count_pattern.py
- test/integration/testvars.py
- test/unit/test_class_index_list.py
Also fix a few other bits
fixes #1044
> Add pattern feature for count filter

- test/unit/test_class_index_list.py
Title says it. Just adding the default case test for the bug you caught on #1067.
Thanks.
> test default case for threshold behavior

- curator/_version.py
- docs/Changelog.rst
- docs/asciidoc/index.asciidoc
- unix_packages/build_official_package.sh
- unix_packages/build_package_from_source.sh
> Release prep for 5.3 beta1

- docs/asciidoc/inc_kinds.asciidoc
- Add missing `exclude: True` in `timestring` docs
> Add missing `exclude: True` in `timestring` docs

- run_curator.py
- run_es_repo_mgr.py
- run_singleton.py
Fixes #
- Improve exception management
- Use docstring of module instead string parameter to print function
> [refactor] improve exception management

- .travis.yml
- setup.cfg
- setup.py
Manage package informations with configuration file
- Use `setup.cfg` to configure python packaging
- Update travis-ci to ensure to use a recent version of setuptools
- Lightweight `setup.py`
> refactor python packaging

- .travis.yml
- requirements.txt
- setup.cfg
- setup.py
Verified it outside of Travis.  Also verified this fix.
> This fixes an oddity in virtualenv builds

- docs/asciidoc/options.asciidoc
Tested doc build and it works
Fixes #1146
> Add missing option documentation

- curator/actions.py
- docs/Changelog.rst
- docs/asciidoc/index.asciidoc
> Add node information missing from log line

- curator/actions.py
- docs/Changelog.rst
- test/unit/test_action_reindex.py
> Disallow empty list for reindex source

- docs/Changelog.rst
- docs/asciidoc/actions.asciidoc
> Warn about using forcemerge on active indices

- docs/Changelog.rst
- docs/asciidoc/installation.asciidoc
> Fix 404s in pip install page

- curator/indexlist.py
- docs/Changelog.rst
- test/integration/test_integrations.py
> Ignore empty indices when using field_stats

- docs/asciidoc/inc_kinds.asciidoc
Fixes # documentation about regex filter
- change a word
-
-
> fixed regex filter documentation

- curator/indexlist.py
cancel and replace https://github.com/elastic/curator/pull/1154
Fixes # https://github.com/elastic/curator/issues/880
Compliance with AWS ES 5.x
> change the source index settings if we don't have the awaited default source

- curator/defaults/filter_elements.py
- curator/defaults/filtertypes.py
- curator/indexlist.py
- curator/snapshotlist.py
- docs/Changelog.rst
- test/unit/test_class_snapshot_list.py
> Add period filter args to snapshot list class

- curator/indexlist.py
- docs/Changelog.rst
- test/unit/test_class_index_list.py
> Update indices the kibana filter catches

- unix_packages/build_official_package.sh
- unix_packages/build_package_from_source.sh
Particularly affecting RHEL/Centos 7
fixes #1124
> Fix openssl-libs dependency for RHEL/Centos 7

- unix_packages/build_official_package.sh
- unix_packages/build_package_from_source.sh
Full test still wasn't working for all 4 builds.  This makes it work on all 4.
> Fix all builds

- .gitignore
- docs/Changelog.rst
A lot of lines were "too long."
> Redo the Changelog with linting on

- .travis.yml
This fixes the build issue.  I still need to manually test
```
python setup.py install
```
and
```
pip install .
```
as part of the release testing.
> Fix builds with this hack (again)

- docs/asciidoc/filters.asciidoc
Fixes #
Update the list of indices comprised by the Kibana filter
> Adapt Kibana filter description

- README.rst
- test/integration/test_delete_indices.py
This is the first draft of documentation changes coming to Curator
> Simplify the README

- docs/asciidoc/examples.asciidoc
- Added reindex to list of examples as it was missing but available in side bar.
> Added reindex to list of available examples.

- .travis.yml
- docs/Changelog.rst
- test/integration/test_delete_indices.py
- travis-run.sh
This may work on the first try.  I guess we'll find out.
> Add tests for ES versions with bundled xpack

- docs/Changelog.rst
Adding the users, PRs and details.
> Update changelog with all of the recent changes

- docs/Changelog.rst
- test/integration/test_delete_indices.py
- test/unit/test_class_index_list.py
> Update ILM version minimum to 6.6.0

- .travis.yml
- curator/cli.py
- docs/Changelog.rst
- requirements.txt
- test/integration/__init__.py
- test/integration/test_delete_indices.py
Which has been a thorn in CI testing since 6.6.0 came out.
> Fix ILM testing

- curator/actions.py
- Add the count of indices + indices names to all actions (Or at least the relevant ones) so its easier to get that info at the beginning of the action execution
> Add indices count + indices names to all actions

- docs/index.rst
Prevents users from accidentally installing [curator](https://pypi.org/project/curator/) (like I did 😊 ).
- Add installation documentation
> Add installation docs

- curator/actions.py
- test/unit/test_action_shrink.py
Fixes #
- Remove multiple patch check from actions.py
- Remove test multiple path module
-
> remove multiple path check

- .travis.yml
- curator/defaults/settings.py
- docs/Changelog.rst
- test/integration/__init__.py
- test/integration/test_create_index.py
- test/integration/test_datemath.py
- test/integration/test_delete_indices.py
- test/integration/test_forcemerge.py
- test/integration/test_integrations.py
- test/integration/test_reindex.py
- test/integration/testvars.py
- test/unit/test_utils.py
- travis-run.sh
At this time, it is testing against release candidate 2
> Add support for Elasticsearch 7.0

- test/integration/test_forcemerge.py
ForceMerges are working, the test just doesn't always catch it properly.
> Fix CI test timing issue

- docs/Changelog.rst
- docs/asciidoc/index.asciidoc
- requirements.txt
- setup.cfg
- setup.py
> Fix urllib3 dependency collision

- docs/asciidoc/ilm.asciidoc
- docs/asciidoc/index.asciidoc
- docs/asciidoc/options.asciidoc
> Add ILM documentation for Curator

- docs/asciidoc/ilm.asciidoc
Check every link next time, mister... 🙄
> Add missing path slash

- curator/cli.py
- curator/exceptions.py
- curator/utils.py
- docs/Changelog.rst
- test/unit/test_utils.py
This is an attempt to make more clear what's going on behind the scenes in issues like #1434. This may or may not fix said issues, but it should improve visibility enough to take additional steps, if needed. Marking the issue as closed, as any further issues will be different.
Fixes #1434
> Update get_client and cli.py client logic

- curator/utils.py
- docs/Changelog.rst
- test/unit/test_utils.py
Initially raised in #510, the issue was addressed in part by @raynigon in #1259. Unfortunately, the one line change was not able to be merged due to many other changes since August 2018. Adaptation and fixes were necessary.
Fixes #510
> Allow connection through proxies

- curator/indexlist.py
Fixes #
- Check if index list is empty before chunk_index_list().
> Add check for empty list to avoid incorrect exception

- curator/utils.py
- docs/Changelog.rst
Fixes #1335 
Please review the same and let me know if anything else we need to do in this.
> changes_done_#1335

- curator/utils.py
- docs/Changelog.rst
- docs/asciidoc/index.asciidoc
- requirements.txt
- setup.cfg
- setup.py
This time it should be for real.
> Release prep for 5.8.0 (again)

- curator/cli.py
- curator/config_utils.py
- curator/defaults/client_defaults.py
- curator/singletons.py
- curator/utils.py
- docs/Changelog.rst
- docs/asciidoc/configuration.asciidoc
- test/unit/test_utils.py
Deprecate http_auth in favor of username and password.
Lots of code clean-up. `get_client` was broken out into separate functions to clean it up, as it was enormous.
> Add username and password to client configuration

- curator/actions.py
- test/integration/test_close.py
Tried (unsuccessfully) to replicate the failure in sdh/8392. Committing the code cleanup anyway.
> Updated for PEP-8 while testing sdh/8392

- curator/cli_singletons/alias.py
- curator/cli_singletons/allocation.py
- curator/cli_singletons/close.py
- curator/cli_singletons/delete.py
- curator/cli_singletons/forcemerge.py
- curator/cli_singletons/freeze.py
- curator/cli_singletons/object_class.py
- curator/cli_singletons/open_indices.py
- curator/cli_singletons/replicas.py
- curator/cli_singletons/restore.py
- curator/cli_singletons/rollover.py
- curator/cli_singletons/show.py
- curator/cli_singletons/shrink.py
- curator/cli_singletons/snapshot.py
- curator/cli_singletons/unfreeze.py
- curator/cli_singletons/utils.py
More of the same code cleanup. This time for the singletons.
> Improve code compliance with PEP-8 (cont'd)

- curator/defaults/filter_elements.py
- curator/defaults/filtertypes.py
- curator/defaults/option_defaults.py
- curator/defaults/settings.py
Cleaned up the defaults this time.
> More code cleanup.

- docs/asciidoc/configuration.asciidoc
I don’t think I need to explain this that much. To reproduce it you need to read the original sentence, and the read the correct one.
> There was a “the” hanging in no mans land

- .travis.yml
- docs/Changelog.rst
- requirements.txt
- setup.cfg
- setup.py
- test/integration/test_delete_indices.py
Can't release until this is done. Many other PRs will need this before they can run.
> Pinning 7.1.0 elasticsearch-py module

- docs/asciidoc/actions.asciidoc
- docs/asciidoc/examples.asciidoc
- examples/actions/unfreeze.yml
Fixes https://github.com/elastic/curator/issues/1479
I am not 100% sure if we support the options (it should as they are the "default" additional options).
Let me know if I should squash the commits.
- Add/fix examples for freeze/unfreeze
- Add documentation on the action page for freeze/unfreeze
> [DOC] Freeze and unfreeze documentation

- curator/exceptions.py
- curator/logtools.py
- docs/Changelog.rst
> Address nested object keys in ECS logging

- .travis.yml
- docs/Changelog.rst
- docs/asciidoc/index.asciidoc
- test/integration/test_allocation.py
- test/integration/test_count_pattern.py
A couple small improvements, but this release will mostly be about the pinned packages for urllib3 and boto.
> Release prep/5.8.2

- .travis.yml
- curator/_version.py
- docs/Changelog.rst
- docs/asciidoc/ilm.asciidoc
- docs/asciidoc/index.asciidoc
- docs/asciidoc/options.asciidoc
Merge in doc fixes, and one merge fail that got missed somehow.
> Tiny patch release to address documentation fails

- curator/defaults/client_defaults.py
- curator/singletons.py
- curator/utils.py
- docs/asciidoc/configuration.asciidoc
- test/unit/test_utils.py
- add new method process_apikey_auth_args method
- update documentation
- add --apikey_auth option to run_singleton.py
#1606
> Add api_key authentication support

- curator/_version.py
- docs/Changelog.rst
- docs/asciidoc/actions.asciidoc
- docs/asciidoc/filters.asciidoc
- docs/asciidoc/ilm.asciidoc
- docs/asciidoc/inc_datemath.asciidoc
- docs/asciidoc/inc_filter_by_aliases.asciidoc
- docs/asciidoc/index.asciidoc
- docs/asciidoc/options.asciidoc
It's going to get merged and pushed!
> This is happening!

- curator/_version.py
- curator/cli.py
- curator/helpers/getters.py
- curator/helpers/testers.py
- docs/Changelog.rst
- docs/asciidoc/index.asciidoc
...as the singleton CLI
This should be great for Docker users to pass values as environment variables
> Update CLI to use same flags for command-line

- .gitignore
- curator/__init__.py
- curator/_version.py
- pyproject.toml
- tests/integration/__init__.py
- tests/unit/test_action_clusterrouting.py
- tests/unit/test_action_create_index.py
- tests/unit/test_action_delete_indices.py
- tests/unit/test_action_delete_snapshots.py
- tests/unit/test_action_forcemerge.py
- tests/unit/test_action_indexsettings.py
- tests/unit/test_action_open.py
- tests/unit/test_action_reindex.py
- tests/unit/test_action_replicas.py
- tests/unit/test_action_restore.py
- tests/unit/test_action_rollover.py
- tests/unit/test_action_shrink.py
- tests/unit/test_action_snapshot.py
- tests/unit/test_class_index_list.py
- tests/unit/test_class_snapshot_list.py
- tests/unit/test_cli_methods.py
Worked fine in Docker. Not so much from pip
> Fix hatch build includes

- curator/_version.py
- curator/actions/__init__.py
- curator/actions/cold2frozen.py
- curator/cli.py
- curator/defaults/option_defaults.py
- curator/defaults/settings.py
- curator/exceptions.py
- curator/helpers/getters.py
- curator/repomgrcli.py
- curator/validators/options.py
- docs/Changelog.rst
- docs/actions.rst
- docs/asciidoc/actions.asciidoc
- docs/asciidoc/index.asciidoc
- docs/helpers.rst
- pyproject.toml
- tests/integration/test_cold2frozen.py
- tests/unit/test_action_cold2frozen.py
Added the new `cold2frozen` action and fixed a few other sundries as outlined in the Changelog
> Release prep for 8.0.3

- curator/_version.py
- curator/indexlist.py
- docs/Changelog.rst
- docs/asciidoc/index.asciidoc
- tests/integration/test_integrations.py
Ready to release 8.0.6 with this.
Fixes #1682
> Fix race condition in get_metadata

- curator/_version.py
- docs/Changelog.rst
- docs/asciidoc/index.asciidoc
- docs/conf.py
- pyproject.toml
Bump Curator version to 8.0.13
Fixes #1708
> Update es_client to 8.12.9

- .gitignore
- curator/_version.py
- curator/actions/shrink.py
- curator/defaults/settings.py
- curator/helpers/getters.py
- docs/Changelog.rst
- docs/asciidoc/index.asciidoc
- docs/conf.py
- tests/unit/test_action_shrink.py
- tests/unit/test_helpers_getters.py
As well as assorted upstream helper functions.
Bump versions in docs and `_version.py` for future release
Update Changelog with most recent changes
Update all touched files to suit pylint formatting
Added `docker_test/.env` to `.gitignore`
> Update node role getting/testing

- Dockerfile
- curator/helpers/date_ops.py
- curator/indexlist.py
- docs/Changelog.rst
- docs/asciidoc/index.asciidoc
- docs/conf.py
- pyproject.toml
- tests/integration/test_delete_indices.py
- tests/unit/test_class_index_list.py
Update Changelog
Fix #1727
Add tests to confirm fix
Update some code formatting issues brought up by Black and Pylint Version bumps everywhere needed for Docs
Fixes #1727
> Release prep for 8.0.17

- docs/reference/configfile.md
Backports https://github.com/elastic/curator/pull/1746
> [8.x][DOCS] fix external links

- .github/workflows/docs-build.yml
Needed to updated the link index.
> Add ability to trigger docs-build manually

- docs/docset.yml
- docs/reference/ilm-or-curator.md
Related to https://github.com/elastic/logstash/pull/17405 
Updates Logstash plugin link.
> [docs] Fix logstash link

- docs/asciidoc/ilm.asciidoc
- Updates links to new MD files
> Doc: Fix links to logstash plugins

- docs/asciidoc/index.asciidoc
- docs/conf.py
> Release prep for 8.0.21

- docs/reference/ilm-actions.md
Updates the /guide links to /docs.
> [DOCS] Updates /guide links to /docs

- docs/reference/ex_restore.md
- docs/reference/ex_rollover.md
- docs/reference/ex_shrink.md
- docs/reference/ex_snapshot.md
- docs/reference/fe_state.md
- docs/reference/fe_value.md
- docs/reference/filtertype_state.md
- docs/reference/option_value.md
- docs/reference/restore.md
- docs/reference/rollover.md
- docs/reference/shrink.md
- docs/reference/snapshot.md
> Modifies H1 titles for better SEO
