elastic/curator

- curator/curator.py
- curator/curator_script.py
The old method of constructing the log messages for the logstash
format produced invalid JSON for certain input. We avoid this by
instead using Python's standard json library for producing the JSON
string. As a bonus this allows us to drop several json.dumps() calls
in the log statements themselves. This addresses issue #248.
> Produce valid JSON for all input with the logstash log format.

- Changelog.rst
- curator/__init__.py
- curator/_version.py
- curator/api/__init__.py
- curator/cli/__init__.py
- curator/curator.py
- curator/es_repo_mgr.py
- setup.py
* setup.py was lacking the new packages "curator.api" and "curator.cli"  The package works now.
* Python3 suggested I had to normalize the beta tag to just b3, so that's also changed.
* Cleaned out superfluous imports and logger references from the __init__.py files.
> V3.0.0b3 release

- curator/api/allocation.py
- curator/api/replicas.py
- curator/api/utils.py
- test/integration/test_api_commands.py
This is an attempt to fix #279. @untergeek: could you please review the changes? Especially the test for changing the replica count of a closed index, as it seems to be already possible without any code change despite calling `prune_closed` (but maybe it's just late and it's not a bug :) So I omitted changing this [`prune_closed`](https://github.com/elasticsearch/curator/blob/master/curator/api/replicas.py#L20) to `ensure_list` for now, but I agree that it would be proper to change that.
ps.: I also think that adding a `prune_replicated` function would be useful to skip the indices that already has the requested replica count (as it is slow to forcibly apply it). I can send a separate PR for that, but since its implementation would probably be related to this changeset, I guess it's a …
> Allow allocation and replicas operations for closed indices

- Changelog.rst
- curator/api/snapshot.py
- curator/api/utils.py
- curator/cli/bloom.py
- curator/cli/cli.py
- curator/cli/index_selection.py
- curator/cli/snapshot_selection.py
- curator/cli/utils.py
- setup.py
- test/integration/test_api_commands.py
- test/integration/test_cli_commands.py
- test/integration/test_cli_utils.py
- test/unit/test_api_utils.py
3.0.0b4 (5 March 2015)
----------------------
**Notes**
Integration testing!  Because I finally figured out how to use the Click
Testing API, I now have a good collection of command-line simulations,
complete with a real back-end.  This testing found a few bugs (this is why
testing exists, right?), and fixed a few of them.
**Bug fixes**
* HUGE! `curator show snapshots` would _delete_ snapshots.  This is fixed.
* Return values are now being sent from the commands.
* `scripttest` is no longer necessary (click.Test works!)
* Calling `get_snapshot` without a snapshot name returns all snapshots
> Beta4 updates

- curator/_version.py
- curator/api/snapshot.py
- curator/api/utils.py
- test/unit/test_api_commands.py
Apparently the method to verify that all nodes have access to the
repository is ES 1.4.0+ only:
`client.snapshot.verify_repository`
Updated a work-around and tested against 1.4.4 and 1.3.4
> Integration testing across ES versions found a bug

- CONTRIBUTORS
- Changelog.rst
- curator/api/utils.py
- curator/cli/index_selection.py
- curator/cli/utils.py
- test/integration/test_cli_commands.py
- test/unit/test_api_commands.py
**Bug fixes**
* Refactored to show `--dry-run` info for `--disk-space` calls. Reported in
#290 (untergeek)
* Added list chunking so acting on huge lists of indices won't result in a URL
bigger than 4096 bytes (Elasticsearch's default limit.)  Reported in
https://github.com/elastic/curator/issues/245#issuecomment-77916081
* Refactored `to_csv()` method to be simpler.
* Added and removed tests according to changes.  Code coverage still at 99%
> Allow ludicrous number of indices in single command (by chunking)

- Changelog.rst
- curator/cli/index_selection.py
- test/integration/test_cli_commands.py
Integration test added to verify that the snapshot command will not split the index list.
fixes #307
> Snapshot command should get full index list

- test/integration/test_cli_commands.py
The big index list test for snapshots can take time, even with the
indices empty.  Timeout errors were seen.  This bump should help
fix that.
> If Jenkins is slow, timeouts can happen

- curator/cli/cli.py
- docs/asciidoc/flags/help.asciidoc
- docs/asciidoc/misc/command-line.asciidoc
Lots of doc updates, now that docs are at http://www.elastic.co/guide/en/elasticsearch/client/curator/current/index.html
> Found a few holdouts still pointing at the wiki

- Changelog.rst
- curator/cli/index_selection.py
- curator/cli/utils.py
The --request-timeout option wasn't working correctly.
The existing tests cover this.
fixes #320
> Reinstate the timeout override from v2

- Changelog.rst
- test/integration/test_cli_commands.py
At least, the failures due to timeouts, since our CI is overloaded
fixes #324
> This will hopefully eliminate Jenkins failures

- Changelog.rst
- curator/cli/index_selection.py
- curator/cli/snapshot_selection.py
- curator/cli/utils.py
- docs/asciidoc/flags/dry-run.asciidoc
- test/integration/test_cli_commands.py
- test/unit/test_cli_utils.py
Several tests died with the code changes, so those tests were
refactored accordingly.  Also, to avoid repetition, some code
was broken out into methods.
All tests passing, 99% code coverage still.
fixes #328
> Improve logging and dry-run output

- curator/cli/index_selection.py
- curator/cli/utils.py
- test/integration/test_cli_commands.py
Add a warning and a countdown (which allows this to still work in
a cron situation, without the need for crazy dialog, Y/N, etc.) in
the event you are filtering by `--timestamp` and not using the
`--older-than` or `--newer-than` flags.  This gives users 10 seconds
to "bow out" before it will act.
Update tests to test this functionality (very passively).
> Proposed fix for #348

- curator/cli/index_selection.py
- curator/cli/snapshot_selection.py
This helps reveal to the user that using `show` will show which
indices or snapshots matched their criteria.
Dry run already makes that more clear, so it doesn't need to be
addressed in this PR.
fixes #293
> Add log notifications for matching items

- Changelog.rst
- curator/api/delete.py
- curator/api/snapshot.py
Log individual index deletes, even though they happen in batches.
Also log individual snapshots.
fixes #372
> Logging improvements

- Changelog.rst
- curator/api/snapshot.py
- test/unit/test_api_commands.py
If `wait_for_completion` is true, snapshot success is now tested and logged.
Also, Log & return false if a snapshot is already in progress
fixes #253
> Test for snapshot success

- curator/api/snapshot.py
This should put the final nail in the coffin.
fixes #379
> There is no _status endpoint before 1.1.0

- Changelog.rst
- curator/api/snapshot.py
- curator/cli/snapshot.py
- curator/cli/utils.py
Do not validate write access to repository on all cluster nodes before
proceeding. Useful for shared filesystems where intermittent timeouts
can affect validation, but won't likely affect snapshot success.
fixes #396
> Add --skip-repo-validation flag

- curator/api/alias.py
- curator/api/allocation.py
- curator/api/bloom.py
- curator/api/close.py
- curator/api/delete.py
- curator/api/opener.py
- curator/api/optimize.py
- curator/api/replicas.py
- curator/api/snapshot.py
This adds the words:
```
Run with --debug flag and/or check Elasticsearch logs for more information.
```
when an error is encountered.
fixes #390
> Recommend running with --debug on errors

- CONTRIBUTORS
- docs/examples.rst
The filter for loop operated on the wrong variable name and the apply_filter method was not being called from the curator object.
> Corrected two errors in the more complex example.

- setup.py
The version needs to be 1.6.0+ to have the synced_flush call.
fixes #447
> Update elasticsearch python module dep

- Changelog.rst
- curator/cli/allocation.py
- test/integration/test_cli_commands.py
I neglected to document #447 in Changelog. Fixed.
There was a commented-out line in allocation.py. Removed.
PR #443 needed a negative test to improve code coverage.
> Added #447 to Changelog, cleaned up, added test

- curator/api/filter.py
- test/unit/test_api_filter.py
Don't know why the original passed on 1.3.4, 1.4.4, and all for me,
but were failing on Jenkins for all ES <1.5.x
Hopefully this fixes the regression.  I can only assume it was
something unusual.
fixes #465
> Regression fix for Jenkins

- test/integration/test_api_commands.py
- test/integration/test_cli_commands.py
Something is different with elasticsearch-py v1.6.0.
Don't know what yet, as it passes on my machine.  This is a first stab
at deciphering it.
> Testing some testing regressions

- Changelog.rst
- test/integration/test_api_commands.py
False alarm.   There were no regressions due to Elasticsearch-py 1.6.0.  It was a Jenkins issue with older python versions.
These have since been updated to 2.7.6 and 3.4.0.
> Regression v160

- curator/api/alias.py
- curator/api/utils.py
Fixes #485 
This is due to change in order of the parameters in `1.7.0` - both `index` and `name` parameters are optional so they need to be referred to as keyword arguments.
> Be explicit when calling exists_alias since order is unreliable

- Changelog.rst
- curator/_version.py
- curator/api/delete.py
- curator/api/filter.py
- curator/cli/index_selection.py
- curator/cli/utils.py
- requirements.txt
- setup.py
- test/unit/test_api_commands.py
- test/unit/test_api_filter.py
- test/unit/test_cli_utils.py
All tests now pass for all versions of ES from 1.0.3 through 2.0.0-rc1
> Massive refactor for Elasticsearch 2.0

- curator/cli/es_repo_mgr.py
These options are already supported by the get_client method.  All
this PR needed was the arguments to be added.
fixes #480
> Update es_repo_mgr to have SSL options

- docs/asciidoc/misc/installation.asciidoc
Since they use the same AWS bucket, it's a legitimate change.  It's also non-breaking as the other will persist for a while.
> Use packages.elastic.co instead

- docs/Changelog.rst
- docs/examples.rst
sphinx-build -b man -d _build/doctrees   . _build/man
Running Sphinx v1.3.1
making output directory...
loading pickled environment... not yet created
building [mo]: targets for 0 po files that are out of date
building [man]: all manpages
updating environment: 6 added, 0 changed, 0 removed
reading sources... [ 16%] Changelog
reading sources... [ 33%] commands
reading sources... [ 50%] examples
reading sources... [ 66%] filters
reading sources... [ 83%] index
reading sources... [100%] utilities
/var/tmp/portage/dev-python/elasticsearch-curator-3.4.0/work/curator-3.4.0/docs/Changelog.rst:45: WARNING: Bullet list ends without a blank line; unexpected unindent.
/var/tmp/portage/dev-python/elasticsearch-curator-3.4.0/work/curator-3.4.0/docs/examples.rst:7: WARNING: Title underline too short.
> Fixing sphinx warnings

- Dockerfile
REPOSITORY                                                    |TAG                    |IMAGE ID            |CREATED             |VIRTUAL SIZE
---                                                    |---                    |---            |---             |---
python                                                        |2.7.8-slim             |609e0e7ecb8a        |12 months ago       |**241.2 MB**
python                                                        |2.7.8                  |481b175a31db        |12 months ago       |800.5 MB
> Use slim version of base image for docker definition

- curator/api/utils.py
- docs/Changelog.rst
- test/unit/test_api_commands.py
- test/unit/test_api_utils.py
And if that yields a 401, then attempt using the _cat API.
This fixes the issue raised in #519
closes #519
> Default to use cluster state first

- docs/Changelog.rst
- setup.py
> Allow python modules elasticsearch>=1.8.0,<2.4.0

- .gitignore
- binary_release.py
- setup.py
```python
python setup.py bdist_msi
```
This will build a Windows installer package in the `dist` subdirectory, which
will have a name like `elasticsearch-curator-3.4.0-win32.msi`.
It will also supply the MD5 and SHA1 checksums for you:
```python
python setup.py build_exe
python binary_release.py
```
This will build binary packages for Linux or Windows, depending on
the operating system at run time.  The resultant output on Linux will look like:
```
Archive: curator-3.4.0-linux-x86_64.tar.gz
curator-3.4.0-linux-x86_64.tar.gz.md5.txt = <md5sum>
curator-3.4.0-linux-x86_64.tar.gz.sha1.txt = <sha1sum>
```
and the resultant output on Windows would look like:
```
Archive: curator-3.4.0-win32.zip
curator-3.4.0-win32.zip.md5.txt = <md5sum>
curator-3.4.0-win32.zip.sha1.txt = <sha1sum>
```
> Setup cx_Freeze to build binary packages

- curator/api/allocation.py
- docs/Changelog.rst
- test/unit/test_api_commands.py
Allocation was exiting with code 1 even with an empty list.  This
differed from other command's behavior, so it has been changed to match.
fixes #531
> Allocation will exit 0 on "empty" lists now

- curator/cli/cli.py
- curator/cli/es_repo_mgr.py
- curator/cli/utils.py
- docs/Changelog.rst
- docs/asciidoc/flags/client-cert.asciidoc
- docs/asciidoc/flags/client-key.asciidoc
- docs/asciidoc/flags/help.asciidoc
- docs/asciidoc/flags/index.asciidoc
- requirements.txt
- setup.py
- test/integration/test_cli_utils.py
- test/unit/test_cli_utils.py
https://github.com/elastic/curator/issues/520
Add support for the `--client-cert` and `--client-key` command
line parameters and client_cert and client_key parameters to
the get_client() call.
NOTE: This depends on
https://github.com/elastic/elasticsearch-py/issues/344
Closes #520
> Add support for client certificates #520

- setup.py
Hi,
We are using some standard commands to fetch data from the setup.py itself like 
$ python setup.py --url
$ python setup.py --description
This is broken since the setup.py is printing stuff when the cx_Freeze import fails.
I agree it's nice to know the import failed, but I think it should be printed somewhere else ?
Thanks,
> Remove print() in setup.py as it breaks commands like "python setup.py --url"

- curator/api/filter.py
no need 'exclude' argument in build_filter, because it is one of 'kindOf' argument in the code
> exclude option in build_filter api

- curator/utils.py
- docs/Changelog.rst
- test/unit/test_utils.py
`.` and `-` need to be escaped, but not other characters.
fixes #602
> Don't escape non-special characters

- curator/actions.py
- curator/cli.py
- curator/settings.py
- curator/utils.py
- docs/Changelog.rst
- docs/asciidoc/actions.asciidoc
- docs/asciidoc/examples.asciidoc
- docs/asciidoc/options.asciidoc
- examples/actions/create_index.yml
- test/integration/test_create_index.py
- test/integration/testvars.py
- test/unit/test_action_alias.py
- test/unit/test_action_allocation.py
- test/unit/test_action_close.py
- test/unit/test_action_create_index.py
- test/unit/test_action_delete_indices.py
- test/unit/test_action_delete_snapshots.py
- test/unit/test_action_forcemerge.py
- test/unit/test_action_open.py
- test/unit/test_action_replicas.py
- test/unit/test_action_snapshot.py
- test/unit/test_utils.py
* Update docs and examples accordingly
* Update tests to reflect a change
Big deal here for the API is adding a `do_dry_run()` method
to the action classes.  Streamlined cli.py some, too.
Bump version to alpha 5
> Add create_indices action

- curator/utils.py
- docs/Changelog.rst
> Fix TimestringSearch to work with Python 2.6

- binary_release.py
This is pretty particular to my own windows machine I use for builds.
If you're trying to use this yourself, you might just want to run
`python setup.py build_exe` or `python setup.py bdist_msi` and use
the resulting files.
> Fix binary_release stuff for windows

- .travis.yml
- travis-run.sh
This mirrors some of what the logstash elasticsearch output plugin does.  This should allow for Travis to do CI testing against multiple Elasticsearch variants.
> Improve Travis to test multiple ES versions

- curator/logtools.py
- docs/Changelog.rst
The `@timestamp` field will now look like this:
```
{"@timestamp": "2016-06-27T11:07:37.906-0600", ... }
```
Hattip @ryancurrah
fixes #661
> Fix logformat json/logstash to send UTC offset

- curator/indexlist.py
- docs/Changelog.rst
- test/unit/test_class_index_list.py
- test/unit/testvars.py
This fixes scenarios where people have older indices and it gives a `KeyError` exception, and can't find `creation_date`.
fixes #663
> Ignore indices with no `creation_date`

- curator/snapshotlist.py
- docs/Changelog.rst
This is an egregious oversight.  It probably trigger an automatic release of 4.0.1
> Fix missing 'state' filter for snapshotlist

- docs/asciidoc/options.asciidoc
Added notes match the existing note for timeout_override, which is one of three settings available for all actions in 4.0.0 version of curator.
> Add note to settings available in all actions

- curator/actions.py
https://github.com/elastic/elasticsearch-py/blob/2.x/elasticsearch/client/cluster.py#L24
```
:arg wait_for_relocating_shards: Wait until the specified number of
relocating shards is finished
```
Fixes #705
> Fix call to cluster health during Allocation wait_for_completion

- README.rst
Curator 4 does not support acting on indices created before Elasticsearch 1.4 as they miss metadata, like `creation_date`.
> Curator 4 excludes indices from < ES 1.4

- CONTRIBUTORS
- curator/utils.py
- docs/Changelog.rst
Corrects https://github.com/elastic/curator/issues/679
The elastic search guides mention aws_region instead of region on the config file.
> Replace region for aws_region in utils.py

- curator/actions.py
- docs/Changelog.rst
- test/integration/test_close.py
- test/unit/test_action_close.py
The method now catches the unexpected exception which resulted if indices _without_ aliases were in the list of indices to have `_all` aliases deleted.
Tests were added to confirm the expected behavior.
fixes #736
> delete_aliases works as expected now

- curator/defaults/settings.py
- curator/indexlist.py
- curator/utils.py
- curator/validators/filter_elements.py
- curator/validators/filters.py
- curator/validators/filtertypes.py
- docs/asciidoc/filter_elements.asciidoc
- docs/asciidoc/filters.asciidoc
- test/integration/test_integrations.py
- test/integration/testvars.py
- test/unit/test_class_index_list.py
- test/unit/test_utils.py
- test/unit/test_validators.py
- test/unit/testvars.py
This feature allows the user to filter an IndexList based on whether the indices are associated with one or more aliases.
This commit also fixes the absence of configuration validation testing for whether filters were appropriate to the list type, i.e. a SnapshotList or IndexList.
Documentation added, tested, and the appropriate tests also added.
fixes #634
> Add alias filtertype

- .travis.yml
- curator/utils.py
- curator/validators/config_file.py
- curator/validators/filter_elements.py
- curator/validators/filters.py
- curator/validators/options.py
- docs/Changelog.rst
- docs/asciidoc/command-line.asciidoc
- docs/asciidoc/configuration.asciidoc
- docs/asciidoc/examples.asciidoc
- docs/asciidoc/filter_elements.asciidoc
- docs/asciidoc/filters.asciidoc
- docs/asciidoc/options.asciidoc
- test/integration/test_envvars.py
- test/integration/testvars.py
- test/unit/test_validators.py
There were quite a few changes that had to go in, including further strictures on the schema, namely `Coerce` to `int` and `float`, since environment variables are all strings.
More tests were added, and the Changelog updated.
Added Elasticsearch 2.4.0 to the list of instances to be tested.
closes #697
> Add support for environment variables

- docs/asciidoc/configuration.asciidoc
The last example was not that helpful (setting a value to the default value).
Updated to make the evaluation behavior more explicit.
> Make the envvars example more explicit

- curator/validators/config_file.py
- curator/validators/filter_elements.py
- curator/validators/options.py
- docs/Changelog.rst
With `Any(bool, int)` in the Schema tests, it will properly report `expected bool` now instead of `expected int` if a non-boolean value was provided.
fixes #757
> Fix error message for boolean values

- docs/asciidoc/examples.asciidoc
When using this example it produces a trackback due to `source` being missing from the younger age filter.
> Add missing `source` to 2nd age filter

- .travis.yml
- docs/Changelog.rst
- requirements.txt
- setup.py
Elasticsearch-py 5.0 is finally out, and it breaks things.  Must fix that before moving on...
fixes #787
> Fix versioning issues

- curator/actions.py
- curator/cli.py
- curator/defaults/settings.py
- curator/utils.py
- curator/validators/actions.py
- curator/validators/options.py
- docs/Changelog.rst
- docs/actionclasses.rst
- docs/asciidoc/actions.asciidoc
- docs/asciidoc/examples.asciidoc
- docs/asciidoc/options.asciidoc
- test/integration/test_clusterrouting.py
- test/integration/testvars.py
- test/unit/test_action_clusterrouting.py
This adds tests and schema validation and documentation (both asciidoc and RST) for this feature.
fixes #446
> Add cluster routing functionality

- setup.py
the settings in `setup.py` point to a non existent module causing all calls to `es_repo_mgr` to end with
```
ImportError: No module named es_repo_mgr
```
> Fix es_repo_mgr path in setup.py

- curator/defaults/settings.py
- docs/Changelog.rst
Curator tests pass with release candidate for 5.1.1
fixes #832
> Bump version_max to 5.1.99

- .travis.yml
- curator/utils.py
- docs/Changelog.rst
- test/unit/test_action_alias.py
- test/unit/test_action_allocation.py
- test/unit/test_action_close.py
- test/unit/test_action_delete_indices.py
- test/unit/test_action_forcemerge.py
- test/unit/test_action_open.py
- test/unit/test_action_replicas.py
- test/unit/test_action_restore.py
- test/unit/test_action_snapshot.py
- test/unit/test_class_index_list.py
- test/unit/test_utils.py
This is a rather manual hack for a limited use case.  It allows the snapshotting of the `.security` index (with proper credentials) but only if you are using 2.4.2 or higher, and lower than 5.x, as this isn't a problem in 5.x
fixes #826
> Enable snapshot of .security in 2.4.2

- docs/Changelog.rst
- test/integration/test_cli.py
This guarantees the test does what it should in either case.
fixes #843
> Fix test when different IP/port are used

- curator/singletons.py
- docs/Changelog.rst
For `snapshot` and `show_snapshot` commands, we usually run them against the entire cluster.
Not sure about providing a string default, it can be fixed at a different level.
> Make filter_list optional

- docs/Changelog.rst
- docs/asciidoc/actions.asciidoc
- docs/asciidoc/configuration.asciidoc
- docs/asciidoc/examples.asciidoc
- docs/asciidoc/faq.asciidoc
- docs/asciidoc/filter_elements.asciidoc
- docs/asciidoc/filters.asciidoc
- docs/asciidoc/inc_filter_chaining.asciidoc
Explain how filters are chained by an implied ogical AND, and a logical OR is only possible with `kind: regex` in `filtertype: pattern`.
[skip ci]
fixes #842
> Improve documentation for filter chaining [skip ci]

- curator/utils.py
- test/unit/test_utils.py
Using isinstance is more robust and allow library user to subclass elasticsearch.Elasticsearch
Also add unittest for verify_client_object function
submitted following https://github.com/elastic/curator/issues/861
> use isinstance instead of type() in verify_client_object

- test/integration/test_alias.py
> Elasticsearch-py 5.1.0 needs get_alias()

- curator/actions.py
- curator/utils.py
- docs/Changelog.rst
- docs/asciidoc/actions.asciidoc
- test/integration/test_reindex.py
Document 5.3.0's issues with ES versions older than 2.0, and that a fix is in 5.3.1. Allow Curator to connect to older clusters by adding "skip_version_test" to the get_client method, and only use it in the remote reindex section.
> Remote reindex issues addressed

- curator/utils.py
- test/unit/test_utils.py
Related to https://github.com/elastic/curator/pull/932
I realized I had a mistake in my code. When comparing two strings, the result was always false for 9 first weeks in the year, because I was not adding leading 0's to the week number, and behaviour was incorrect. I added new tests to demonstrate it.
I had also to remove the comparison to support the case of the ISO leap year (53 weeks, but 52 in Gregorian). Ex:2009 week 53.
```
>>> week53 = datetime.strptime("2009.W531", "%Y.W%W%w")
>>> week53
datetime.datetime(2010, 1, 4, 0, 0)
>>> datetime.strftime(week53, "%Y.W%W%w")
'2010.W011'
>>> week53.isocalendar()
(2010, 1, 1)
```
The above example was working because the iso_week_str was missing a leading 0. In conclusion, it is not because iso week number and gregorian week number are the …
> Fixed ISO week parsing code in utils

- curator/actions.py
- docs/Changelog.rst
- test/integration/test_reindex.py
Since you can reindex to an alias, the previous behavior was to test for the absence of an index.  The fix is to have an `and` condition that also tests for the absence of an alias named the same as the target.
fixes #941
> Test if target index is alias for reindex action

- docs/Changelog.rst
- docs/asciidoc/filter_elements.asciidoc
- docs/asciidoc/inc_strftime_table.asciidoc
- docs/asciidoc/options.asciidoc
> Document substitute strftime symbols for ISO Weeks

- .travis.yml
- curator/indexlist.py
- docs/Changelog.rst
- test/integration/test_delete_indices.py
This edge case is addressed by testing to see if a value is integer, rather than truthiness.
fixes #951
> Fix epoch 0 name-based filtering

- docs/asciidoc/options.asciidoc
Most new users get bit by this, and `ignore_empty_list` is actually what they want.
> Explain 2 exception types, and to use the other

- docs/asciidoc/installation.asciidoc
The APT repository doesn't include information for arch=i386, so ensure the deb line doesn't try to index files for i386.
> Ensure APT sources.list line only use arch=amd64

- requirements.txt
- setup.py
Curator couldn't be installed when mock wasn't present in the python path. Adding it as a requirement and as a dependency installation can be performed succesfully without the user having to "pip install mock".
Congratulations on your development!
> Mock library added

- curator/actions.py
- docs/Changelog.rst
The default is 10 seconds, which may not be enough for remote reindex to pull all of the indices and metadata (especially over a remote connection).
Setting it to 180 seconds.
fixes #930
> Increase remote client timeout from default

- docs/asciidoc/faq.asciidoc
- docs/asciidoc/versions.asciidoc
Update compatibility and FAQ to indicate that Curator can do index management with AWS ES 5.3 but not yet support snapshot management.
> Doc update regarding AWS ES and snapshots

- docs/asciidoc/examples.asciidoc
This filter appears to still be required, at least in my experience. This action will continue to re-process indices that have already been force merged. Perhaps this documentation refers to a forthcoming release.
> Fix note about 'forcemerged' filter

- .travis.yml
- curator/indexlist.py
- docs/Changelog.rst
- docs/asciidoc/filter_elements.asciidoc
- docs/asciidoc/filters.asciidoc
- docs/asciidoc/index.asciidoc
- test/integration/test_integrations.py
Mostly documentation, but allow one test to respond differently based on which version of ES it sees.
fixes #1021
> Address API change in ES 5.5.0

- docs/asciidoc/actions.asciidoc
- docs/asciidoc/options.asciidoc
Changing index settings should be under the header `index_settings` rather than merely `settings` like with other actions.
This is clear in the [official Elasticsearch documentation](https://www.elastic.co/guide/en/elasticsearch/reference/current/modules-snapshots.html#_changing_index_settings_during_restore).
fixes #1015
> Fix documentation for extra_settings in restore

- docs/asciidoc/examples.asciidoc
I think this should be 'index.blocks.write' so 'blocks' with an 's'.
This just tripped me when trying out the new features in 5.1.2.
> Fix typo in index settings example action file

- curator/actions.py
- test/integration/test_rollover.py
Allow usage of date variables in the new_index option for the rollover action.
> Allow dates in new_index value for rollover action

- curator/actions.py
replace {0} with self.shrink_node
Previously, logging looked like this, because the string was never formatted:
```2017-09-20 16:51:15,396 INFO      Node "{0}" has multiple data paths and will not be used for shrink operations.```
> format error correctly

- docs/asciidoc/options.asciidoc
Add information about the option hitting master-eligible nodes along with the elected master.
As discussed in https://github.com/elastic/curator/issues/1068
> Better explain the sub-option permit_masters

- Changelog.rst
- curator/singletons.py
- docs/Changelog.rst
- same options as snapshot supported, plus rename_pattern and rename_replacement
- tested against elasticsearch 5x
part of #851
> Add a restore action to curator_cli

- curator/defaults/filter_elements.py
- curator/defaults/filtertypes.py
- curator/defaults/settings.py
- curator/indexlist.py
- docs/asciidoc/filter_elements.asciidoc
- docs/asciidoc/filters.asciidoc
- test/unit/test_class_index_list.py
Addresses https://github.com/elastic/curator/issues/1066
I'm not attached to the `index_comparison` key at all, and hope there's a better name for it. I'm open to suggestions.
I'm not very familiar with asciidoc, so I hope I did that part right. If you want me to make any changes, just let me know.
Thanks a lot for Curator. It's a great tool, and I make heavy use of it.
> [FEATURE] Add support for returning indices smaller than `disk_space` in space filter

- Changelog.rst
- curator/repomgrcli.py
- curator/utils.py
- docs/Changelog.rst
Sometimes (when we want to restore a backup) we don't want to verify the repository after creation.
Adding a flag to es_repo_mgr script, allowing us to disable the check, by passing `--verify false`.
> Add a verify option to es_repo_mgr create

- Changelog.rst
- curator/actions.py
Code was doing a client lookup for each name making it very slow to determine which node to use.
> Use cached stats result to lookup names

- Changelog.rst
- curator/defaults/client_defaults.py
- curator/utils.py
- docs/asciidoc/configuration.asciidoc
- unix_packages/build_official_package.sh
- unix_packages/build_package_from_source.sh
Using the get_credentials definition, we can get credentials from the local environment.
Definition: http://boto3.readthedocs.io/en/latest/reference/core/session.html#boto3.session.Session.get_credentials
Order in which credentials is searched: http://docs.aws.amazon.com/cli/latest/userguide/cli-chap-getting-started.html#config-settings-and-precedence
> Add support for AWS IAM authentication using boto3

- .gitignore
- setup.py
isn't copied to the target directory.
This workaround is better than the broken "official" method for cx_freeze.
> Fix reported issue where vcruntime140.dll

- curator/indexlist.py
- test/unit/test_class_index_list.py
Exclude=False was not keeping only matching indices.
Note: PR opened against 5.x per author request in PR #1106
> Fix 'filter_kibana' to use correctly 'exclude' argument

- curator/utils.py
Hi!,
I'm configuring curator against an AWS ES using a CNAME registry and it's failing when the certificate is being validated (as the domain name it's different). I can see in the code that curator doesn't respect the value of the `ssl_no_validate` config param in this specific case.
I'm deleting the override as I don't see any reason to force the value to be True
> Stop overriding verify_certs param in AWS ES

- Dockerfile
Tested and verified working against the 5.4 branch. Does however not work against master right now, because build_exe isn't working in master.
We publish our image here: https://quay.io/repository/lalamove/elasticsearch-curator
> Dockerfile that builds from source and produces slim image

- curator/defaults/option_defaults.py
And it's fixed for all supported versions of voluptuous over 0.9.3, rather than needing to pin voluptuous to 0.10.5
fixes #1149
> These changes fix voluptuous schema validation

- .travis.yml
- docs/Changelog.rst
- setup.cfg
- setup.py
- travis-run.sh
This updates tested versions and removes support for Python 3.4, which is no longer supported or updated.
> Update CI and changelog

- curator/actions.py
- curator/utils.py
- docs/Changelog.rst
- docs/asciidoc/options.asciidoc
- test/integration/test_alias.py
- test/integration/test_datemath.py
- test/integration/test_snapshot.py
- test/unit/test_utils.py
Usable in alias and snapshot actions now where the `name` parameter is used.
Fixes #1078
> Add date math support

- docs/Changelog.rst
- docs/asciidoc/filter_elements.asciidoc
- docs/asciidoc/inc_sources.asciidoc
Which no longer appears in 6.x
> Fix doc links to field_stats API

- curator/defaults/option_defaults.py
- docs/Changelog.rst
- docs/asciidoc/options.asciidoc
This helps with the case identified in #1133
Fixes #1133
> Add timeout_override for delete_snapshots

- curator/utils.py
- docs/Changelog.rst
The exception is being raised, but no message shown when multiple hosts are specified and `master_only` is set to true.
> Last minute addition to log an error

- curator/actions.py
- docs/Changelog.rst
Ordering of the filter_closed and empty_list_check were resulting in an empty list being passed to the action.
fixes #1180
> Fix Replicas and Forcemerge to check closed first

- docs/asciidoc/options.asciidoc
This addresses the unnecessary option_ in `option_migration_prefix` and `option_migration_suffix` links.
> Remove option_ prefix to migration prefix/suffix

- curator/indexlist.py
- test/integration/test_delete_indices.py
Fixes #1206 
Introduce and extra boolean to keep track of indices that failed to match the pattern without changing the value for _exclude_ for the rest of the loop execution.
Added a test case that forces the bug to happen with non-fixed code.
> #1206 - The unit_count_pattern setting can cause indices to mistakenly be included in an index filter

- docs/asciidoc/filters.asciidoc
Doc fix to make it more obvious how to include the matched indices.
It might not currently be as obvious as it could be:
- https://discuss.elastic.co/t/curator-allocated-filtertype-does-not-seem-to-work/118899/8
- https://discuss.elastic.co/t/curator-allocation-filters/128437
So hopefully this reduces some amount of headscratching.
> Clarify inclusive filtering for allocated filter

- .travis.yml
- curator/actions.py
- docs/Changelog.rst
- requirements.txt
- setup.cfg
- setup.py
- test/unit/test_action_alias.py
If `ignore_empty_list` is `true`, Curator should respect that and not raise an `ActionError`
Did some virtualenv testing and found that not specifying `six` in requirements.txt resulted in execution errors.
Restored the `before_install` block to `.travis.yml`.  Before this, it worked for _each_ run, _except_ for the elasticsearch 6.2.4 tests, which I cannot explain.  Best to keep it, since it works.
fixes #1209
> Fix ignore_empty_list with Alias action

- curator/defaults/filtertypes.py
- curator/defaults/settings.py
- curator/indexlist.py
- docs/asciidoc/filters.asciidoc
It is now possible to filter empty indices. Simply exposing the function that already existed.
```
- filtertype: empty
exlude: True|False
```
> Exposed filter_empty function as a filter

- curator/utils.py
- docs/Changelog.rst
- test/unit/test_cli_methods.py
This should have been here a long time ago.  It kind of was, but something about how Click was being used and the other methods being wrapped caused it to be hidden.
This brings what was hidden back into plain sight.
Fixes #1237
> Fix YAML linting/error display

- CONTRIBUTORS
- curator/utils.py
- test/unit/test_utils.py
Fixes #1295 
Classify all timestamp with 11 to 13 digits as epoch + milliseconds
> allow old epoch timestamps with 11-13 digits as epoch + milliseconds

- docs/Changelog.rst
- docs/asciidoc/examples.asciidoc
Wording fixes and a typo. Remove superfluous disable_action line.
> Fix rollover example text

- curator/exceptions.py
- curator/utils.py
- docs/Changelog.rst
- test/integration/test_reindex.py
This addresses the failure scenario outlined so clearly in the listed issue.
A similar mapping error was injected as a new integration test to prove that an exception will be raised in the future.
fixes #1260
> Catch reindex failures and raise an exception

- curator/indexlist.py
- curator/snapshotlist.py
- test/unit/test_class_index_list.py
- test/unit/test_class_snapshot_list.py
Fixes #1354 
Issue says it all really: currently regex pattern filters only match against the start of the index name.  The prefix / suffix patterns are fine because they get wrapped with ^<prefix>.*$ etc.
> Use re.search() not re.match() in pattern filter so regex doesn't have to be a prefix

- Dockerfile
Fixes wget errors when getting https pages
- Run update-ca-certificates and upate wget package. Without these changes you get the following error when try to get a HTTPS site
$ wget https://site.org
wget: error getting response: Connection reset by peer
> Update wget version in Dockerfile

- curator/indexlist.py
- Fix typos that were causing incorrect rendering. Addresses all Sphinx warnings.
> Fix docs typos in filter_period

- .travis.yml
- LICENSE.txt
- docs/Changelog.rst
- docs/asciidoc/index.asciidoc
- docs/asciidoc/versions.asciidoc
- docs/index.rst
- requirements.txt
- setup.cfg
- setup.py
Using `elasticsearch-py` 7.0
Update docs, travis CI, etc.
> Release prep for Curator 5.7

- Dockerfile
- requirements.txt
- setup.cfg
- setup.py
We need to urllib3 >= 1.24.2 and requests >= 2.20.0 to address the
following CVEs.
urllib3:
CVE-2018-20060 9.8 Fixed >= 1.23
CVE-2019-11324 7.5 Fixed >= 1.24.2
requests:
CVE-2018-18074 9.8 Fixed >= 2.20.0
Additionally cleanup the Dockerfile to no longer pre-install
dependencies that are already covered in requirements.txt to avoid
re-installing/conflicting dependencies.
Fixes: #1394
Fixes #
- Adjust requirements to address above CVEs.
> Update urllib3, requests requirements

- docs/asciidoc/filters.asciidoc
The default value of `exclude` option is `true`.
https://github.com/elastic/curator/blob/5.7/curator/indexlist.py#L876
> Update count filter docs

- docs/asciidoc/options.asciidoc
Related to https://github.com/elastic/elasticsearch/pull/43493, which adds an explicit anchor ID for the restore section here:
https://www.elastic.co/guide/en/elasticsearch/reference/master/modules-snapshots.html#restore-snapshot
As a result, all of these links that used the auto-generated anchor ID break:
> INFO:build_docs:Bad cross-document links:
INFO:build_docs:  /tmp/docsbuild/target_repo/html/en/elasticsearch/client/curator/4.0/option_rename_pattern.html:
INFO:build_docs:   - en/elasticsearch/reference/current/modules-snapshots.html#_restore
INFO:build_docs:  /tmp/docsbuild/target_repo/html/en/elasticsearch/client/curator/4.0/option_rename_replacement.html:
INFO:build_docs:   - en/elasticsearch/reference/current/modules-snapshots.html#_restore
INFO:build_docs: …
> [DOCS] Fixes broken link

- docs/asciidoc/options.asciidoc
Related to #1426.
With https://github.com/elastic/elasticsearch/pull/43493, we added an explicit anchor ID for the restore section here:
https://www.elastic.co/guide/en/elasticsearch/reference/master/modules-snapshots.html#restore-snapshot
As a result, all of these links that used the auto-generated anchor ID break:
> INFO:build_docs:Bad cross-document links:
INFO:build_docs:  /tmp/docsbuild/target_repo/html/en/elasticsearch/client/curator/5.7/option_rename_replacement.html:
INFO:build_docs:   - en/elasticsearch/reference/7.0/modules-snapshots.html#_restoreINFO:build_docs:  /tmp/docsbuild/target_repo/html/en/elasticsearch/client/curator/5.x/option_rename_replacement.html:
INFO:build_docs:   - en/elasticsearch/reference/7.0/modules-snapshots.html#_restore
INFO:build_docs: …
> [DOCS] Fix broken link

- curator/indexlist.py
- docs/Changelog.rst
- docs/asciidoc/filters.asciidoc
- When using the [empty](https://www.elastic.co/guide/en/elasticsearch/client/curator/current/filtertype_empty.html) filtertype, automatically exclude closed indices from consideration. This will allow users to use the empty filtertype in a cluster with closed indices and not accidentally target them.
> Exclude closed indices from consideration when using the empty filter

- curator/actions.py
- curator/utils.py
- docs/Changelog.rst
It was considering replicas until this fix.
Fixes #1431
> Fix shrink action to count only primary shard sizes

- curator/cli.py
- curator/utils.py
- docs/Changelog.rst
- test/integration/test_rollover.py
Now `allow_ilm_indices` affects rollover aliases as would be expected.
Fixes #1418
> Disallow ILM by default with the rollover action

- curator/actions.py
- curator/cli_singletons/close.py
- curator/defaults/option_defaults.py
- curator/validators/options.py
- docs/Changelog.rst
- docs/asciidoc/actions.asciidoc
- docs/asciidoc/examples.asciidoc
- docs/asciidoc/options.asciidoc
- test/integration/__init__.py
- test/integration/test_close.py
- test/integration/testvars.py
- test/unit/test_action_close.py
Fixes #1412
- Added a `skip_flush` option for the `close` action, defaults to `False`.
> add skip_flush option for close action

- curator/snapshotlist.py
- curator/utils.py
- docs/Changelog.rst
- test/integration/test_delete_snapshots.py
This prevents the error described in #1366 where this value did not exist.
Fixes #1366
> Catch empty/None values for snapshots without ages

- curator/utils.py
- docs/Changelog.rst
When connecting in the `get_client()` function, ensure that all TransportError type exceptions are properly caught and the messages reported properly, too.
Fixes #1413
> Report 40x errors properly

- Dockerfile
- curator/utils.py
- docs/Changelog.rst
Fixes #1360 
- Changed to query all indices instead of a comma separated list of indices.
- The logic checks restoration of only the indices passed as a list, out of
the status of all indices
> Fix crashes in restore of "large" number of indices

- .travis.yml
- docs/Changelog.rst
- docs/asciidoc/actions.asciidoc
- docs/asciidoc/examples.asciidoc
- docs/asciidoc/versions.asciidoc
- examples/actions/unfreeze.yml
- requirements.txt
- setup.cfg
- setup.py
- test/integration/test_delete_indices.py
As mentioned in #1478
> Shows that Curator 5 is compatible with ES 7. However, a customer running Curator 5.6 found that it was not compatible with ES 7.2.
> 
> Obviously this is because ES 7.2 (or indeed any 7.x) didn't exist when Curator 5.6 was released. However, the Matrix seems to suggest that ANY Curator 5 will work with ES 7.x. Now, if I change the docs version to Curator 5.6, then the ES 7.x column disappears, so it's correct. But a Google search tends to take you to the latest doc, so I can understand how the customer made the mistake.
Fixes #1478
Split the matrix for 5 into two sections --> 5.6- and 5.7+ and updated the compatibility for ES7.x
> Curator 5.6 is not compatible with ES 7.2

- curator/actions.py
Fixes #
Related to issue #1494.
With this fix, when we're shrinking we're doing as shown by the ES [documentation](https://www.elastic.co/guide/en/elasticsearch/reference/7.6/indices-shrink-index.html#_shrinking_an_index) : 
```
POST /my_source_index/_shrink/my_target_index
{
"settings": {
"index.routing.allocation.require._name": null, 
"index.blocks.write": null 
}
}
```
Hence, the shrink index operation doesn't hang anymore because of the routing requirement.
It seems that all tests be played against a single ES instance.
This use case requires a cluster in order to reproduce this error with integration tests (need help).
> Fix the hang of the shring method with ES 7.x

- curator/cli_singletons/utils.py
- curator/defaults/client_defaults.py
- curator/logtools.py
- curator/singletons.py
- docs/asciidoc/command-line.asciidoc
- docs/asciidoc/configuration.asciidoc
Add ECS log format to curator, which is just JSON but with field names defined in the Elastic Common Schema.
Fixes #1519
> Add ECS log format

- .travis.yml
- curator/utils.py
- docs/Changelog.rst
- test/unit/test_action_delete_snapshots.py
- test/unit/test_utils.py
In older releases (< 7.5) of ES Python module, `client.tasks.get()` will return a list of all tasks. However, starting in 7.5, this results in a failed API call. See https://github.com/elastic/elasticsearch-py/issues/1110
Correct behavior is to use `client.tasks.list()` when no task id is provided.
> Ensure proper API call is used

- docs/asciidoc/options.asciidoc
date math in ES is using java time where Y changed to y
this is in ES version 7.0 and newer
> Update examples with index templates

- requirements.txt
- setup.cfg
- setup.py
Fixes #1560 Fixed #1559 
- Change the upper bound on `urllib3` to <1.26 to allow `botocore` 1.19.x to install without dependency conflicts.
> Update urllib3 upper pin to <1.26

- curator/actions.py
- docs/asciidoc/actions.asciidoc
- docs/asciidoc/options.asciidoc
Updates several links to the [Changing index settings during restore](https://www.elastic.co/guide/en/elasticsearch/reference/master/snapshots-restore-snapshot.html#change-index-settings-during-restore) section of the ES reference. These work due to a redirect, but this will improve the UX.
> [DOCS] Update restore snapshot index setting links

- Dockerfile
- curator/utils.py
- test/unit/test_utils.py
Fixes #1535
- use aws_region variable in boto3 session if available
- add XML dependency to parse sts web token responses
> support regional STS endpoint usage, add AWS EKS IRSA dependencies

- curator/utils.py
- requirements.txt
- setup.cfg
- setup.py
- test/unit/test_class_index_list.py
- test/unit/test_class_snapshot_list.py
This is yet another trial at bumping PyYAML to latest version.  Various efforts have failed due to compatibility issues but I wanted to make one more try, since it looked to me like it might work now.
Motivation: Many CVEs have been reported for PyYAML which are now found by vulnerability scanners when scanning the system with the old PyYAML version:
* https://nvd.nist.gov/vuln/detail/CVE-2020-14343
* https://nvd.nist.gov/vuln/detail/CVE-2020-1747
* https://nvd.nist.gov/vuln/detail/CVE-2019-20477
* https://nvd.nist.gov/vuln/detail/CVE-2017-18342
> Version bump to pyyaml 5.4.1

- curator/actions.py
- curator/defaults/filter_elements.py
- curator/defaults/filtertypes.py
- curator/defaults/settings.py
- curator/indexlist.py
- test/integration/test_shrink.py
- test/unit/test_class_index_list.py
- test/unit/testvars.py
Fixes  #1151
- Add size filter type to filter indices based on their their primary only size or total size.
> Add filter by size

- .readthedocs.yaml
Trying to get modules installed for ReadTheDocs build to show content.
> Add the Python settings to RTD yaml file

- docs/asciidoc/actions.asciidoc
- docs/asciidoc/options.asciidoc
Fixes the `8.0` and `current` build failures of https://github.com/elastic/docs/pull/2611
> Fix broken doc links

- curator/actions/__init__.py
- curator/classdef.py
- curator/cli.py
- curator/repomgrcli.py
- docker_test/scripts/create.sh
- docker_test/scripts/destroy.sh
- docs/Changelog.rst
- docs/api.rst
- docs/asciidoc/command-line.asciidoc
- docs/classdef.rst
- docs/conf.py
- docs/helpers.rst
- docs/other_modules.rst
- docs/usage.rst
- pyproject.toml
- tests/integration/__init__.py
- tests/integration/test_cli.py
**Changes**
* Added the same CLI flags that the singletons offers. This gives much more flexibility with
regards to passing configuration settings as command-line options, particularly for Docker.
* Re-created the ``get_client`` function. It now resides in ``curator.helpers.getters`` and will
eventually see use in the Reindex class for remote connections.
* Created a new set of classes to import, validate the schema, and split individual actions into
their own sub-object instances. This is primarily to make ``curator/cli.py`` read much more
cleanly. No new functionality here, but fewer conditional branches, and hopefully more readable
code.
* Updated the documentation to show these changes, both the API and the Elastic.co usage docs.
> Ready to release 8.0.2

- setup.py
Fixes #
The docker build is currently broken due to a breaking change in the latest cx_freeze, which removes camelCasing from the Executable parameters.
The latest cx_freeze (6.15.0) is automatically pulled in during the pip3 installation on alpine.
https://github.com/marcelotduarte/cx_Freeze/releases/tag/6.15.0
https://github.com/marcelotduarte/cx_Freeze/commit/8a3dc177c53800008f2cbf365750edb25859cdf9
> Update targetName to match the latest cx_freeze release (6.15.0)

- Dockerfile
This is a follow-up to #1679. The build failed due to outdated pip.
Sorry I missed this in the previous PR.
> Add pip upgrade command during the build of the docker container

- setup.py
Similar to #1679 
The docker build is currently broken due to a breaking change in the latest cx_freeze, which removes camelCasing from the Executable parameters.
The latest cx_freeze (6.15.0) is automatically pulled in during the pip3 installation on alpine.
https://github.com/marcelotduarte/cx_Freeze/releases/tag/6.15.0
https://github.com/marcelotduarte/cx_Freeze/commit/8a3dc177c53800008f2cbf365750edb25859cdf9
> Update cx_freeze params

- .dockerignore
- Dockerfile
- curator/_version.py
- curator/cli.py
- curator/helpers/waiters.py
- curator/indexlist.py
- curator/logtools.py
- docs/Changelog.rst
- docs/asciidoc/index.asciidoc
- docs/conf.py
- pyproject.toml
- setup.py
- tests/integration/test_cli.py
- tests/integration/test_integrations.py
**Changes**
* Small PEP formatting changes that were found editing code.
* Bump Python version in Dockerfile to 3.11.4
* Bump Python dependency versions.
* Change ``targetName`` to ``target_name`` in ``setup.py`` for newest version
of cx_Freeze. Hat tip to ``@rene-dekker`` in #1681 who made these changes
to 5.x and 7.x.
* Fix command-line behavior to not fail if the default config file is not
present. The newer CLI-based configuration should allow for no config file
at all, and now that's fixed.
* Initial work done to prevent a race condition where an index is present at IndexList
initialization, but is missing by the time index stats collection begins. The resultant
404s were causing Curator to shut down and not complete steps.
* When running in a Docker container, make Curator log to …
> Release prep for 8.8.2

- .gitignore
- curator/_version.py
- curator/actions/index_settings.py
- curator/indexlist.py
- docs/Changelog.rst
- docs/asciidoc/index.asciidoc
- tests/integration/test_create_index.py
- tests/integration/test_forcemerge.py
- tests/integration/test_integrations.py
- tests/unit/test_action_alias.py
- tests/unit/test_action_allocation.py
- tests/unit/test_action_close.py
- tests/unit/test_action_cold2frozen.py
- tests/unit/test_action_delete_indices.py
- tests/unit/test_action_forcemerge.py
- tests/unit/test_action_indexsettings.py
- tests/unit/test_action_open.py
- tests/unit/test_action_reindex.py
- tests/unit/test_action_replicas.py
- tests/unit/test_action_restore.py
- tests/unit/test_action_rollover.py
- tests/unit/test_action_shrink.py
- tests/unit/test_action_snapshot.py
- tests/unit/test_class_index_list.py
- tests/unit/test_helpers_utils.py
- tests/unit/testvars.py
There are no changes in this release that change how Curator will appear to behave to the user. However...
This release ends the practice of collecting all stats and metadata at IndexList initiation. This should make execution much faster for users with enormous clusters with hundreds to thousands of indices. In the past, this was handled at IndexList instantiation by making a cluster state API call. This is rather heavy, and can be so much data as to slow down Curator for minutes on clusters with hundreds to thousands of shards. This is all changed in this release.
For example, the pattern filter requires no index metadata, as it only works against the index name. If you use a pattern filter first, the actionable list of indices is reduced. Then if you need to filter based on age using …
> Release prep for 8.0.7

- curator/_version.py
- curator/helpers/utils.py
- curator/indexlist.py
- docs/Changelog.rst
- docs/asciidoc/index.asciidoc
- tests/integration/test_integrations.py
- tests/unit/test_class_index_list.py
**Announcements**
Small change to further reduce memory usage by not creating unused data structures.
This revealed a glitch with dry-runs that would eventually have been reported.
**Changes**
* Don't populate IndexList.index_info until required by a filter. In other words, stop populating the zero values as part of instantiation.
* This uncovered an oversight with the 8.0.7 release. Certain actions, if taken with no filters, or only a pattern filter, would never ever populate the index_info. This wasn't a huge problem, unless you were using the dry-run flag. The dry-run output requires the index_info to be present for each index. In 8.0.7, where the empty structure was already in place, a dry-run wouldn't fail, but it also wouldn't show any data. This is fixed.
* A few tests also needed …
> Release prep for 8.0.8

- pyproject.toml
Elasticsearch Curator 7.x fails to install (tested on Python 3.9 & 3.10) as the `pyyaml` requirement of 6.0.0 fails:
```
Collecting pyyaml==6.0.0
Using cached PyYAML-6.0.tar.gz (124 kB)
Installing build dependencies ... done
Getting requirements to build wheel ... error
ERROR: Command errored out with exit status 1:
[...]
File "/tmp/pip-build-env-8g9pbe4r/overlay/lib/python3.9/site-packages/setuptools/_distutils/cmd.py", line 107, in __getattr__
raise AttributeError(attr)
AttributeError: cython_sources
----------------------------------------
ERROR: Could not find a version that satisfies the requirement pyyaml==6.0.0 (from elasticsearch-curator) (from versions: 3.10, 3.11, 3.12, 3.13b1, 3.13rc1, 3.13, 4.2b1, 4.2b2, 4.2b4, 5.1b1, 5.1b3, 5.1b5, 5.1, 5.1.1, 5.1.2, 5.2b1, 5.2, 5.3b1, 5.3, …
```
> Bump `pyyaml` requirement to 6.0.1

- .dockerignore
- .gitignore
- Dockerfile
- curator/_version.py
- curator/actions.py
- curator/indexlist.py
- curator/utils.py
- docs/Changelog.rst
- docs/asciidoc/index.asciidoc
- docs/conf.py
- pyproject.toml
**Changes**
* This release brings some Python modules up to current releases, namely:
* ``certifi>=2023.5.7``
* ``click==8.1.4``
* ``elasticsearch7==7.17.9``
* ``pyyaml==6.0.1``
* The PyYAML change is notable as the Cython 3.0 upgrade caused it to no longer work.
Version 6.0.1 fixes that, enabling Curator to build again.
* ``cx_Freeze`` changed some configurations to be more Pythonic. #1681 fixes that.
> Updates for 7.0.1 release

- curator/_version.py
- docs/Changelog.rst
- docs/conf.py
- pyproject.toml
Bump Curator version to 8.0.10
Bump es_client dependency to 8.12.4 to address Docker logging permissions issue
> Version bumps

- docs/asciidoc/inc_datemath.asciidoc
elasticsearch has changed to use y instead of Y as it migrated to use java.time
this is in ES version 7.0 and newer
> Update date math section to use y instead of Y

- docs/asciidoc/filters.asciidoc
Update period filtertype description to correctly reflect the possible options for `unit` referenced in https://www.elastic.co/guide/en/elasticsearch/client/curator/current/fe_unit.html as `hours`, `days`, `weeks`, `months`, or `years` only.
Fixes #1549
> Update period filtertype description

- .dockerignore
On development when you change Dockerfile and run building Docker image, it starts from scratch, because with command "COPY . ." Dockerfile is copied too which forces Docker Builder to ignore building cache. We can prevent that by adding .dockerignore file with added line "Dockerfile". In future more files could be added to .dockerignore to increase build speed.
> add .dockerignore to increase build speed

- docs/asciidoc/inc_kinds.asciidoc
Clarify that values of `prefix` and `suffix` filter kinds are not taken literally but rather a regexp is constructed from them.
This is important difference if index names are using dots (or other special characters).
For example, with  prefix of `value: project.prod-a.` the index `project.prod-admin-portal.2020.10.15` is matched. By reading the documentation this is unexpected as the impression is that prefix and suffix should be used literally.
> [docs] clarification on prefix and suffix kinds

- docs/testing.rst
- pyproject.toml
- tests/integration/test_es_repo_mgr.py
- tests/unit/__init__.py
- tests/unit/test_action_alias.py
- tests/unit/test_action_allocation.py
- tests/unit/test_action_close.py
- tests/unit/test_action_clusterrouting.py
- tests/unit/test_action_cold2frozen.py
- tests/unit/test_action_create_index.py
- tests/unit/test_action_delete_indices.py
- tests/unit/test_action_delete_snapshots.py
- tests/unit/test_action_forcemerge.py
- tests/unit/test_action_indexsettings.py
- tests/unit/test_action_open.py
- tests/unit/test_action_reindex.py
- tests/unit/test_action_replicas.py
- tests/unit/test_action_restore.py
- tests/unit/test_action_rollover.py
- tests/unit/test_action_shrink.py
- tests/unit/test_action_snapshot.py
- tests/unit/test_class_index_list.py
- tests/unit/test_class_snapshot_list.py
- tests/unit/test_helpers_date_ops.py
- tests/unit/test_helpers_getters.py
- tests/unit/test_helpers_testers.py
- tests/unit/test_helpers_utils.py
- tests/unit/test_helpers_waiters.py
Since Python 3.3 the unittest module provides mock.
- Use unittest.mock instead of an external mock dependency
> Use build in unittest.mock

- curator/_version.py
- docs/Changelog.rst
- docs/asciidoc/index.asciidoc
- docs/conf.py
- pyproject.toml
**Bugfix**
* ``six`` dependency erroneously removed from ``es_client``. It's back in ``es_client==8.12.8``
> Release 8.0.12

- Dockerfile
- curator/_version.py
- curator/actions/alias.py
- curator/helpers/date_ops.py
- curator/indexlist.py
- docker_test/.env
- docker_test/scripts/create.sh
- docker_test/scripts/destroy.sh
- docs/Changelog.rst
- docs/asciidoc/index.asciidoc
- docs/conf.py
- pyproject.toml
- tests/integration/__init__.py
- tests/integration/test_alias.py
- tests/integration/test_datemath.py
- tests/integration/test_snapshot.py
- tests/unit/test_helpers_date_ops.py
**Announcement**
* Python 3.12 support becomes official. A few changes were necessary to ``datetime`` calls
which were still using naive timestamps. Tests across all minor Python versions from 3.8 - 3.12
verify everything is working as expected with regards to those changes. Note that Docker builds
are still running Python 3.11 as cx_Freeze still does not officially support Python 3.12.
* Added infrastructure to test multiple versions of Python against the code base. This requires
you to run:
* ``pip install -U hatch hatchling`` -- Install prerequisites
* ``hatch run docker:create X.Y.Z`` -- where ``X.Y.Z`` is an ES version on Docker Hub
* ``hatch run test:pytest`` -- Run the test suite for each supported version of Python
* ``hatch run docker:destroy`` -- Cleanup the Docker containers …
> Release prep for 8.0.15

- curator/indexlist.py
There is an unescaped character in the docstring of `indexlist` module which has been [deprecated since Python 3.6](https://docs.python.org/3/whatsnew/3.6.html#deprecated-python-behavior).
This causes an issue during `pytest`'s test collection phase when running tests on modules that import curator as a library on later versions of Python: `"SyntaxError: invalid escape sequence '\d'"`
In popular python linters e.g. ruff and flake8 this [violates rule W605](https://docs.astral.sh/ruff/rules/invalid-escape-sequence/).
Upon linting the entire source code, this is the only file that has this rule violation. This commit fixes this error.
The change has been tested by modifying a local copy of the library and running my test suite that originally failed against it, and the exception no longer …
> Fix unescaped characater error in docstring

- pyproject.toml
Fixes #1701 
- Update `pyyaml` package pin from `6.0.0` to `6.0.1` (which supports PEP-517 for modern build systems) specifically for `6.x` releases.
> fix(#1701): Bump pyyaml requirement to 6.0.1 for PEP-517.

- curator/cli.py
This PR fixes some (forgotten?) debug statements logged with CRITICAL level.
Example output of a normal curator 8.0.15 run:
```
Jul  4 06:00:09 elk01 curator[527005]: 2024-07-04 06:00:09,741 CRITICAL  INITIAL Action kwargs: {}
Jul  4 06:00:09 elk01 curator[527005]: 2024-07-04 06:00:09,741 CRITICAL  Post search_pattern Action kwargs: {'ignore_unavailable': False, 'include_global_state': True, 'partial': False, 'repository': 'my_backup', '
skip_repo_fs_check': False, 'wait_for_completion': True, 'max_wait': -1, 'wait_interval': 9, 'name': 'curator-%Y%m%d%H%M%S'}
Jul  4 06:00:09 elk01 curator[527005]: 2024-07-04 06:00:09,886 CRITICAL  Pre Instantiation Action kwargs: {'ignore_unavailable': False, 'include_global_state': True, 'partial': False, 'repository': 'my_backup', 'sk …
```
> Fix wrong log level for several debug messages

- .gitignore
- curator/_version.py
- curator/actions/reindex.py
- curator/classdef.py
- curator/cli.py
- curator/cli_singletons/delete.py
- curator/defaults/filter_elements.py
- curator/defaults/option_defaults.py
- curator/defaults/settings.py
- curator/helpers/date_ops.py
- curator/helpers/testers.py
- curator/singletons.py
- curator/validators/actions.py
- docker_test/.env
- docs/Changelog.rst
- docs/asciidoc/index.asciidoc
- docs/conf.py
- docs/helpers.rst
- mypy.ini
- pyproject.toml
- pytest.ini
- tests/integration/test_reindex.py
- tests/unit/test_helpers_waiters.py
**Changes**
* Update to use ``es_client==8.14.2``
* Formatting changes and improvements
* Update CLI to get client using ``ctx.obj['configdict']`` as it's already built
by ``es_client``.
**Bugfixes**
* Fix improper log levels erroneously left in from debugging. Thanks to
@boutetnico in #1714
* ``es_client`` version 8.14.2 addresses a problem where Python 3.8 is not officially supported
for use with ``voluptuous`` greater than ``0.14.2``.
> Release prep for 8.0.16

- docs/docset.yml
- docs/reference/ilm-or-curator.md
- docs/reference/index_settings.md
Follow up to https://github.com/elastic/curator/pull/1737
When using cross-repo links, the path should be relative to the docset.yml not the full path within the repo ([updated docs-builder docs](https://elastic.github.io/docs-builder/syntax/links/#cross-repository-links)).
> [docs] Clean up cross-repo links

- docs/reference/configfile.md
Fix external links that incorrectly use `.md` instead of `.html`.
> [docs] Fix external links

- docs/reference/configfile.md
- docs/reference/ex_reindex.md
- docs/reference/option_remote_certificate.md
- docs/reference/option_remote_client_cert.md
- docs/reference/option_remote_client_key.md
- docs/reference/option_remote_filters.md
- docs/reference/option_remote_url_prefix.md
- docs/reference/option_request_body.md
In light of finding abuse of dummy links in our docs, this replaces placeholder URLs with non-hostable segments. 
Rel: https://github.com/elastic/docs-content/issues/1799
> Replace placeholder URLs
